sudo: required

services:
  - docker

script:
  - docker build -t go-starter-kit-compile -f build/Dockerfile.build .
  - docker run --name appBuilder go-starter-kit-compile /bin/sh -c "make lint;"
  # Copy the compiled binary out of the container
  - docker cp appBuilder:/go/bin/app .
  - docker build -t go-starter-kit -f build/Dockerfile .


# install:
#   - npm install -g codecov
#   - npm install
# script:
# - npm run lint
# - npm run test
# - npm run coverage
# - codecov

notifications:
  email: false

# ./bin/app run -c production > /dev/null